### ISSUE TITLE
[Critical bug] hover/focus/click are broken when changing --parallel or stories order

### ISSUE THREAD

**Issue by sag1v** [reg-viz/storycap#580]
# Reproduction

First clone [this repo](https://github.com/sag1v/storycap-test) and install dependencies

```bash
git clone https://github.com/sag1v/storycap-test.git
cd storycap-test
npm install
```

## Run Tests

In order to run tests, run:

```bash
npm run tests:visual
```

⚠️ Attention: Depending on your local chromium version, tests should pass. If they don't pass due to font rendering or spaces you can update them with:

```bash
npm run tests:visual:update
```

You should see these images:

![image](https://user-images.githubusercontent.com/9153149/160099447-e707e473-7dcb-4c80-8170-f8ae164e6957.png)

## Reproduce the bug

After you see that the tests are passing, go to `capture.sh` script and change the `--parallel` to 1:

```diff
- storycap --serverCmd "http-server storybook-static -p 9009" --outDir "integration/__screenshots__" --parallel 4 http://localhost:9009
+ storycap --serverCmd "http-server storybook-static -p 9009" --outDir "integration/__screenshots__" --parallel 1 http://localhost:9009
```

Now run the tests again

```bash
npm run tests:visual
```

## Expected behavior

All tests are passing

## Actual behavior

`Focus` image is changed and failed (the button is no longer focused)

![image](https://user-images.githubusercontent.com/9153149/160099795-ca684012-69b4-4d49-bbd9-bba8e341f1cc.png)

## Debugging

In `Button.stories.jsx` file, comment out the `click` parameter for the `Click` story.  

```diff
Click.parameters = {
  screenshot: {
    // comment this line to fix the "Focus" story image test when storycap runs with --parallel 1
-   click: "#btn",
+   //click: "#btn",
  },
};
```

We should expect to see 2 tests failing now right? `Focus` (like before) and `Click`.  
Well, no. Now only `Click` test is failing (as it should) but `Focus` is back to normal and passes (as it should) 🤷

![image](https://user-images.githubusercontent.com/9153149/160100199-04257741-766e-43a4-b3bd-43100a9da801.png)

If you want, you can add a mouse tracker to the page to see where is the mouse position while screenshot is taken.  
In `./storybook/preview.js` file, add the `withMouseTrack` decorator:

```diff
- export const decorators = [withScreenshot]
+ export const decorators = [withScreenshot, withMouseTrack];
```

Run the tests again:

```bash
npm run tests:visual
```

## Conclusion

I suspect that when we run tests on the same page instance, the events are shared and persistent across stories, this is why changing an event in one story affect another or when we run multiple instances in parallel we don't see issues (it depends on the number of tests we have because i do have inconsistency issues with ~300 tests).

I think that [this section](https://github.com/reg-viz/storycap/blob/45683e138edb5b48cec75ac91663bf3bef650356/packages/storycap/src/node/capturing-browser.ts#L123) where we reset the page state, isn't working well.

```js
 private async resetIfTouched() {
    const story = this.currentStory;
    if (!this.touched || !story) return;
    this.debug('Reset story because page state got dirty in this request.', this.currentRequestId);
    await this.setCurrentStory(story, { forceRerender: true });

    // Clear the browser state.
    await this.page.hover('body');
    await this.page.focus('body');
    await this.page.click('body');

    this.touched = false;

    return;
  }
```

I'm not sure why but i think that we need to reset the page even if page wasn't touched, but i'm not sure.

**Comment by sag1v** [comment]
@Quramy What do you think is the issue here?

**Comment by Quramy** [comment]
Thanks, I’ll review in this weekend!

**Comment by sag1v** [comment]
> Thanks, I’ll review in this weekend!

Cool thanks 👍

If you do accept this solution and merge then i hope you will merge it to 3.5.x and not only to the alpha version (see #576)

**Comment by Quramy** [comment]
@sag1v Thanks for your reporting and PR.
I've merged and published as v3.1.6

**Comment by sag1v** [comment]
> @sag1v Thanks for your reporting and PR.
> I've merged and published as v3.1.6

Thanks @Quramy ! Unfortunately it didn't solve the issue i have in my project, i still get unexpected focus/hover states. Its a tough to reproduce on a clean repo though. 😞
