### ISSUE TITLE
Support Chromium newest versions

### ISSUE THREAD

**Issue by stanislav215** [reg-viz/storycap#896]
From Chromium 128.0.6613.18 version, getting error:

/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:194
            reject(new Error([
                   ^

Error: Failed to launch the browser process!

Related to package: "puppeteer-core": "^9.0.0" in storycap/packages/storycrawler

Please add support.

**Comment by K-kind** [comment]
I encountered a similar issue in my project after the Chrome version of GitHub Actions was updated yesterday. The following error caused Storycap to stop working:

```
TimeoutError: Navigation timeout of 60000 ms exceeded
```

As a temporary solution, it can be fixed using the previous version of Chrome.

```yml
- name: Install Chrome
        id: chrome
        uses: browser-actions/setup-chrome@facf10a55b9caf92e0cc749b4f82bf8220989148 # v1.7.2
        with:
          chrome-version: 127
- name: Take Screenshots
  env:
    CHROME_PATH: ${{ steps.chrome.outputs.chrome-path }}
  run: npm run ci:screenshot
```

package.json

```json
"ci:screenshot": "storycap http://localhost:6007 --chromiumPath $CHROME_PATH --serverCmd 'http-server storybook-static --ci -p 6007'"
```

**Comment by debiru** [comment]
Today, I encountered this problem in my projects.

My project is running Storybook v6.5 and v7.x, and we will updating to Storybook v8.x.

It appears that this problem occurs with the latest version of Chrome (128) in combination with Storybook v8.x.

| Storybook | Chrome 127 | Chrome 128 |
| :---: | :---: | :---: |
| v6.5 | OK | OK |
| v7.x | OK | OK |
| v8.x | OK | Occured this problem |

I would like to get a solution.

**Comment by Quramy** [comment]
Hi. 

I'm investigating this issue. But I still can't find how to fix this.

I can reproduce the following error, which is the same message of https://github.com/reg-viz/storycap/issues/896#issuecomment-2317248668:

```
TimeoutError: Navigation timeout of 60000 ms exceeded
```

- This error occurs on GHA CI (`ubuntu-latest` runner, Chromium: `linux-128.0.6613.86`)
- This error does not occur in my local macbook (Chromium: `mac_arm-128.0.6613.86` installed via `npm i puppeteer` )
- This error does not occur for webpack based Storybook. It only occurs for Storybook built by Vite.
  - Storycap's implementation is agnostic for "how to build Storybook". I don't know why the kind of module bundler affects this error 🤔 
- Upgradeing `puppeteer-core` package does not solve this issue.

**Comment by Quramy** [comment]
@K-kind @debiru 

I suppressed the navigation timeout error on Chromium 128 and shipped as pre-patch version, https://www.npmjs.com/package/storycap/v/5.0.1-alpha.0 .

Would you try this and check if your timeout error goes away?

**Comment by k35o** [comment]
@Quramy 
I had the same problem, but was able to solve it by using the `5.0.1-alpah.0` version.Thanks for shipping!

> This error does not occur for webpack based Storybook. It only occurs for Storybook built by Vite

As written above, I'm using a webpack based Storybook and I get the same error.

**Comment by Quramy** [comment]
@k35o 

> I had the same problem, but was able to solve it by using the 5.0.1-alpah.0 version.Thanks for shipping!

Thanks for your reply 😄  I'll merge #902 and ship `storycap@5.0.1` soon.

**Comment by Quramy** [comment]
@stanislav215 (and others)

I've closed this issue, but I could not reproduce your " Error: Failed to launch the browser process! " rejection.
I fixed only the navigation timeout error problem(https://github.com/reg-viz/storycap/issues/896#issuecomment-2317248668)

If you're encountering the `Failed to launch the browser process! `, please re-open this issue. 🙏

**Comment by AndrewStobie** [comment]
I am still getting the timeout error with storycap `5.0.1` chromium `128` storybook `^8` that is webpack based fwiw...
